package com.tale.uder.integration_tests.api;

import android.support.annotation.NonNull;
import com.squareup.okhttp.mockwebserver.MockResponse;
import com.squareup.okhttp.mockwebserver.MockWebServer;
import com.tale.uder.UderIntegrationRobolectricTestRunner;
import com.tale.uder.api.UderRestApi;
import com.tale.uder.api.entities.DirectionResponse;
import com.tale.uder.models.DirectionModel;
import java.io.IOException;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import retrofit.HttpException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;

/**
 * Main purpose of Integration tests is to check that all layers of your app work correctly, for
 * example:
 * <ul>
 * <li>Http layer</li>
 * <li>REST layer</li>
 * <li>Parsing/Serializing layer</li>
 * <li>Execution layer (ie RxJava)</li>
 * </ul>
 */
@RunWith(UderIntegrationRobolectricTestRunner.class) public class UderRestApiIntegrationTest {
  private static final String SAMPLE_RESPONSE = "{\n"
      + "   \"geocoded_waypoints\" : [\n"
      + "      {\n"
      + "         \"geocoder_status\" : \"OK\",\n"
      + "         \"place_id\" : \"EkIzMCDEkOG7lyBOaHXhuq1uLCBTxqFuIEvhu7MsIFTDom4gUGjDuiwgSOG7kyBDaMOtIE1pbmgsIFZp4buHdCBOYW0\",\n"
      + "         \"types\" : [ \"street_address\" ]\n"
      + "      },\n"
      + "      {\n"
      + "         \"geocoder_status\" : \"OK\",\n"
      + "         \"place_id\" : \"ChIJyw_-DMAudTERO_GHQhEXmYA\",\n"
      + "         \"types\" : [\n"
      + "            \"bus_station\",\n"
      + "            \"transit_station\",\n"
      + "            \"point_of_interest\",\n"
      + "            \"establishment\"\n"
      + "         ]\n"
      + "      }\n"
      + "   ],\n"
      + "   \"routes\" : [\n"
      + "      {\n"
      + "         \"bounds\" : {\n"
      + "            \"northeast\" : {\n"
      + "               \"lat\" : 10.8042539,\n"
      + "               \"lng\" : 106.6532502\n"
      + "            },\n"
      + "            \"southwest\" : {\n"
      + "               \"lat\" : 10.7687234,\n"
      + "               \"lng\" : 106.6256764\n"
      + "            }\n"
      + "         },\n"
      + "         \"copyrights\" : \"Dữ liệu bản đồ ©2016 Google\",\n"
      + "         \"legs\" : [\n"
      + "            {\n"
      + "               \"distance\" : {\n"
      + "                  \"text\" : \"6,0 km\",\n"
      + "                  \"value\" : 5981\n"
      + "               },\n"
      + "               \"duration\" : {\n"
      + "                  \"text\" : \"19 phút\",\n"
      + "                  \"value\" : 1136\n"
      + "               },\n"
      + "               \"end_address\" : \"70 Lữ Gia, phường 15, Quận 11, Hồ Chí Minh\",\n"
      + "               \"end_location\" : {\n"
      + "                  \"lat\" : 10.7711066,\n"
      + "                  \"lng\" : 106.6532502\n"
      + "               },\n"
      + "               \"start_address\" : \"30 Đỗ Nhuận, Sơn Kỳ, Tân Phú, Hồ Chí Minh, Việt Nam\",\n"
      + "               \"start_location\" : {\n"
      + "                  \"lat\" : 10.8042539,\n"
      + "                  \"lng\" : 106.6256764\n"
      + "               },\n"
      + "               \"steps\" : [\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,3 km\",\n"
      + "                        \"value\" : 298\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 51\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.8029422,\n"
      + "                        \"lng\" : 106.6278457\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Đi về hướng \\u003cb\\u003eĐông Nam\\u003c/b\\u003e lên \\u003cb\\u003eĐỗ Nhuận\\u003c/b\\u003e về phía \\u003cb\\u003eĐỗ Nhuận\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Công Ty Tnhh Thương Mại Dịch Vụ An Hùng Cường (ở phía bên phải)\\u003c/div\\u003e\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"qe}`AoixiSB?@?@ABCBKFW@CBMDg@BMDWFIFCHCXEPERIJIJKHQ@i@^q@N[LYBKFONi@\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.8042539,\n"
      + "                        \"lng\" : 106.6256764\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"39 m\",\n"
      + "                        \"value\" : 39\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 14\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.8025914,\n"
      + "                        \"lng\" : 106.6278055\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e tại Công Ty Tnhh Thương Mại Dịch Vụ Sản Xuất Hà Nguyễn vào \\u003cb\\u003eSơn Kỳ\\u003c/b\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"k}|`AawxiSdAF\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.8029422,\n"
      + "                        \"lng\" : 106.6278457\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"64 m\",\n"
      + "                        \"value\" : 64\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 18\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.8027039,\n"
      + "                        \"lng\" : 106.6283769\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003etrái\\u003c/b\\u003e tại Cửa Hàng Nguyên Ký vào \\u003cb\\u003eTân Kỳ Tân Quý\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Công Ty Tnhh Thương Mại Dịch Vụ Việt Cam (ở phía bên trái)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-left\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"e{|`AyvxiSUqB\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.8025914,\n"
      + "                        \"lng\" : 106.6278055\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,3 km\",\n"
      + "                        \"value\" : 262\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 42\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.8005132,\n"
      + "                        \"lng\" : 106.6275268\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e tại Công Ty Tnhh Đại Quang Rạng Đông vào \\u003cb\\u003eNguyễn Quý Anh\\u003c/b\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"{{|`AkzxiSn@HRBB@h@Jr@PD@nAZPH^PB@@?z@`@@?bA\\\\\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.8027039,\n"
      + "                        \"lng\" : 106.6283769\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,5 km\",\n"
      + "                        \"value\" : 516\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"2 phút\",\n"
      + "                        \"value\" : 96\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7983937,\n"
      + "                        \"lng\" : 106.6316553\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003etrái\\u003c/b\\u003e tại Công Ty Tnhh Dịch Vụ Du Lịch Ánh Sao Việt vào \\u003cb\\u003eNguyễn Cửu Đàm\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Đen Coffee (ở bên phải cách 400&nbsp;m)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-left\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"en|`AauxiSJDTm@~@cCfAoCZy@BGb@eA`AcCFOd@kA^_Ah@uA\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.8005132,\n"
      + "                        \"lng\" : 106.6275268\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"29 m\",\n"
      + "                        \"value\" : 29\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 10\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7986049,\n"
      + "                        \"lng\" : 106.6318069\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003etrái\\u003c/b\\u003e tại Công Ty Cp Aci Tt Sài Gòn vào \\u003cb\\u003eTân Sơn Nhì\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Nhà Hàng Thức Ăn Nhanh Kfc (ở phía bên phải)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-left\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"}`|`A{nyiSKG[SAA\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7983937,\n"
      + "                        \"lng\" : 106.6316553\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,2 km\",\n"
      + "                        \"value\" : 250\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 47\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7970098,\n"
      + "                        \"lng\" : 106.632975\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e tại Công an phường Tân Sơn Nhì vào \\u003cb\\u003eDiệp Minh Châu\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Công Ty Tnhh Mtv Thương Mại Dịch Vụ Thành Trần (ở phía bên phải)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"gb|`AyoyiSh@cAl@iAz@{ANI@AJCJA~@FLBH@N@V@\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7986049,\n"
      + "                        \"lng\" : 106.6318069\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,2 km\",\n"
      + "                        \"value\" : 174\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 33\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7969682,\n"
      + "                        \"lng\" : 106.6344104\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003etrái\\u003c/b\\u003e tại Công Ty Tnhh Mtv Tm Thủy Sản Biển Xanh vào \\u003cb\\u003eNguyễn Thế Truyện\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Công Ty Tnhh Tm - Dv Tư Vấn Đăng Khoa (ở phía bên trái)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-left\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"ix{`AcwyiS\\\\@G}AK}CAc@\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7970098,\n"
      + "                        \"lng\" : 106.632975\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,5 km\",\n"
      + "                        \"value\" : 453\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"2 phút\",\n"
      + "                        \"value\" : 97\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7969554,\n"
      + "                        \"lng\" : 106.6379657\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e vào \\u003cb\\u003eTrần Tấn\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Beauty Salon Ngọc Thu (ở phía bên phải)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"ax{`Aa`ziSH?FCDCFGV_@p@_BHIBC@C?C?GAMo@c@]YGECKEKMs@]uAEOCGAIBOBQNi@Ru@FOBG@AWgB\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7969682,\n"
      + "                        \"lng\" : 106.6344104\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"3,5 km\",\n"
      + "                        \"value\" : 3491\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"11 phút\",\n"
      + "                        \"value\" : 655\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7690366,\n"
      + "                        \"lng\" : 106.6518372\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e tại Công Ty Tnhh Dịch Vụ Tư Vấn Đức Hòa vào \\u003cb\\u003eÂu Cơ\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eBăng qua Ngân Hàng Công Thương Việt Nam (Vietinbank) - Pgd Số 1 (ở bên phải cách 400&nbsp;m)\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"_x{`AivziSfB[jB]r@CJCFGHGDCl@MfASnJuBdAWpHmBxEcA`D{@vA[fAWh@MTGh@I`@KdCo@`FyAjA]|Ag@^KhDw@zA[r@OdCi@t@Sl@ShBk@RIZMhC_BBA|CkBx@g@ZS`Am@\\\\UNKLIjBgAHElAw@v@c@\\\\U\\\\SVQf@]LIn@e@FCt@c@DETOXSxAeApA_AHEBCjAs@LG|@k@NIJGpCeBbAk@xBqAv@c@j@[rAs@RMh@Wh@]dAo@vA_ARMdAq@n@a@TQTKPITKh@U\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7969554,\n"
      + "                        \"lng\" : 106.6379657\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"0,3 km\",\n"
      + "                        \"value\" : 330\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 55\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7709062,\n"
      + "                        \"lng\" : 106.6526785\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Tại vòng xuyến, đi theo lối ra \\u003cb\\u003ethứ 3\\u003c/b\\u003e vào \\u003cb\\u003eNguyễn Thị Nhỏ\\u003c/b\\u003e\",\n"
      + "                     \"maneuver\" : \"roundabout-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"oiv`A_m}iSD@D?D?DADG@EBI@KBMBGFIDKBI?MAG?EGGGCEAKCKDA@}@Gy@EM@[CyDSg@C\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7690366,\n"
      + "                        \"lng\" : 106.6518372\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"41 m\",\n"
      + "                        \"value\" : 41\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 9\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7711579,\n"
      + "                        \"lng\" : 106.6529464\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Đi \\u003cb\\u003ebên phải\\u003c/b\\u003e để đi tiếp về hướng \\u003cb\\u003eLữ Gia\\u003c/b\\u003e\",\n"
      + "                     \"maneuver\" : \"keep-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"euv`Agr}iSOKWWIQ\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7709062,\n"
      + "                        \"lng\" : 106.6526785\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  },\n"
      + "                  {\n"
      + "                     \"distance\" : {\n"
      + "                        \"text\" : \"34 m\",\n"
      + "                        \"value\" : 34\n"
      + "                     },\n"
      + "                     \"duration\" : {\n"
      + "                        \"text\" : \"1 phút\",\n"
      + "                        \"value\" : 9\n"
      + "                     },\n"
      + "                     \"end_location\" : {\n"
      + "                        \"lat\" : 10.7711066,\n"
      + "                        \"lng\" : 106.6532502\n"
      + "                     },\n"
      + "                     \"html_instructions\" : \"Rẽ \\u003cb\\u003ephải\\u003c/b\\u003e tại Cửa Hàng Trang Sức Pnj vào \\u003cb\\u003eLữ Gia\\u003c/b\\u003e\\u003cdiv style=\\\"font-size:0.9em\\\"\\u003eĐiểm đến sẽ ở bên trái\\u003c/div\\u003e\",\n"
      + "                     \"maneuver\" : \"turn-right\",\n"
      + "                     \"polyline\" : {\n"
      + "                        \"points\" : \"wvv`A}s}iSH{@\"\n"
      + "                     },\n"
      + "                     \"start_location\" : {\n"
      + "                        \"lat\" : 10.7711579,\n"
      + "                        \"lng\" : 106.6529464\n"
      + "                     },\n"
      + "                     \"travel_mode\" : \"DRIVING\"\n"
      + "                  }\n"
      + "               ],\n"
      + "               \"via_waypoint\" : []\n"
      + "            }\n"
      + "         ],\n"
      + "         \"overview_polyline\" : {\n"
      + "            \"points\" : \"qe}`AoixiSD?DEPu@Hu@DWFIPGj@K^ST]@i@^q@\\\\u@J[Ni@dAFUqBn@HVDrDz@v@\\\\lCdAxD{JpBaFdAkCh@uAKG]UvAmCz@{ANILEjADVDf@B\\\\@G}AMaEPCLKV_@p@_BLM@GAUmA}@GECKS_Ai@wBFa@b@_BJWUiBrEy@~@GPOr@QvLiCvJeCxEcA`D{@~Cs@jCk@fJiChDeAhEcAnCk@zD}@vC_An@WlCaBtHuEtIkFjBmArBsAzEiDfBeAjFcD|D}BbB_AzDwBvFoDdAs@f@U~@a@J@JAFMHc@Tg@AUGMMEKCKD_AEgACuEWg@COKa@i@H{@\"\n"
      + "         },\n"
      + "         \"summary\" : \"Âu Cơ\",\n"
      + "         \"warnings\" : [],\n"
      + "         \"waypoint_order\" : []\n"
      + "      }\n"
      + "   ],\n"
      + "   \"status\" : \"OK\"\n"
      + "}";

  @SuppressWarnings("NullableProblems") // Initialized in @Before.
  @NonNull private MockWebServer mockWebServer;

  @SuppressWarnings("NullableProblems") // Initialized in @Before.
  @NonNull private UderRestApi uderRestApi;

  @Before public void beforeEachTest() throws IOException {
    mockWebServer = new MockWebServer();
    mockWebServer.start();

    // Change base url to the mocked
    UderIntegrationRobolectricTestRunner.udersApp()
        .applicationComponent()
        .changeableBaseUrl()
        .setBaseUrl(mockWebServer.url("").toString());

    uderRestApi = UderIntegrationRobolectricTestRunner.udersApp().applicationComponent().udersApi();
  }

  @After public void afterEachTest() throws IOException {
    mockWebServer.shutdown();
  }

  @Test public void items_shouldHandleCorrectResponse() {
    mockWebServer.enqueue(new MockResponse().setBody(SAMPLE_RESPONSE));

    // Get items from the API
    final DirectionResponse response =
        uderRestApi.getDirection("origin", "destination", DirectionModel.API_KEY)
            .toBlocking()
            .value();

    assertThat(response.routes).hasSize(1);
    assertThat(response.routes.get(0).legs).hasSize(1);
    assertThat(response.routes.get(0).legs.get(0).steps).hasSize(13);
  }

  // Such tests assert that no matter how we implement our REST api:
  // Retrofit or not
  // OkHttp or not
  // It should handle error responses too.
  @Test public void items_shouldThrowExceptionIfWebServerRespondError() {
    for (Integer errorCode : HttpCodes.clientAndServerSideErrorCodes()) {
      mockWebServer.enqueue(new MockResponse().setStatus("HTTP/1.1 " + errorCode + " Not today"));

      try {
        uderRestApi.getDirection("origin", "destination", DirectionModel.API_KEY)
            .toBlocking()
            .value();
        fail("HttpException should be thrown for error code: " + errorCode);
      } catch (RuntimeException expected) {
        HttpException httpException = (HttpException) expected.getCause();
        assertThat(httpException.code()).isEqualTo(errorCode);
        assertThat(httpException.message()).isEqualTo("Not today");
      }
    }
  }
}
